travis:
  secure:
    BINSTAR_TOKEN: iEkMTa6ZkTl4RbChso/JGHsMsnwOsS5TF10NhSM7d2/LbqE4Rt2O3puqqjIoLbP0BnofYSDPmah/1H7BwHChF06DFIaZRbxMpI4Qq3P1gtBqbqK+xC1e4ftQaGVnHjxCCK8xlg1rtugh8SLUaSvw2lcww6hogdTnDvYyRQ/gCi32/m04w0MBtuSLk5sCqW6z1Ql7x7/qJQ6P3N2bkW3wJMBCqm63Y1iuPneX5u4WyAXfpDPc63SGplPb4oMFIvBEHU/5oMGIio/IFV044G54Hhd7jOp4JEkYfQkf9lo5l+Ap6RXocHXMYxGzk8uzX+LBKIH9ZNM2Rb4oHOyIoyC1HEIGiNkmV4rOmieuZZfz/ykrbcbvtTQzVg4JV5o5TRInV90Madd/lD7enwC7s6ksjn4sBO53C/28/wyjz/IJIVYCkLvcaMNN2qXUKHshtqr9oa9Jl44z37ArVOn+wBfjfQ3TLvn7gHyVcBRLcgo6m994JnXSKdObKP3kt+Ms7sflC58E3XbCaneJfEoDJlvXN/K0Vrn5lpEHXOF5szlC291b8ifJO4w6qhlHzyGxiTu5K75B6nbY2gQQUo0+c6rP5JH5JOVRFfXbO/uwsaRaaaCSNFTUmKiQM/3fKhNUlq2HzUNUGUGJqTCRiVhexYAFj9tKelp9w4eJ5L2Ca45LrTQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
