travis:
  secure:
    BINSTAR_TOKEN: VtNjYelr1cN7hU647U/u79YT6buO1hgY1zReXQtsp2ifucrOQq6Sc/ayWd+w9tedhEljBZggRKjWbGGIpapyGRcezWIM8jsASgT7kLH6FSz3eqbijPTJApb2eGRCqa0dZ3t0807xzE0a/x/xIxtZnb0mKktZ/92Y/ujXcWHtrxGCqGcYSF63UqWOe/9waagPl2sI4yuYDxaYaY9uSl6HKDxvqUMA8EbBHrQil3VwojhnnD9FNHQXTjjrvMOp0injpil1HJb4JmfJEVvLHxSU0vEcPbZomrXccI2UVC9LrSbk9Q6erTdUBpmZmpDbqq79s7jT116B2TaJtsp0r/j1KSPLsA6qcsNBXUDC/4KjL/g5A6NnKhFM8E+UFgFwu44ohQqvQ3lHN5gwHAd0DN5XVL9NrV2R1o6YStGIpng6hBxse1c/t+O34mEr06SSNuw21jUq4r44luj3bCTkD2ODCsmPmMATmt5gA33zgYxS4e70BIpEcxUn6wSAdDbxi+ahJ78SQ7O6yfMn5doNgq3uIAABI3yx6rW/LOq52QWPANj6BmZaD8P3tCBsiFjZl+ZVtBDBjRFpQgiZS05N1re6EtHPD08TFjjRcy3jv5m8v2WMnV8yF5+WEfL/elgFE6E/RS6+Dc2S5Oj4txlNl0EimRsvPKPbFUA5yt9NbPmpM5g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
